Haggle/urls.py
from django.urls import path

from .views import (contactPage, faq, 
                    Home, PriceCompareView, SearchResultView, 
                    profilecard, ProductListView, landing_page
)


from . import views
from django.contrib.auth import views as auth_views




app_name = "Haggle"


urlpatterns = [
    path('', landing_page, name='landing' ),
    #AUTHENTICATION
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name ="users\password_reset.html"), name='password_reset'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name ="users\password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name ="users\password_reset_form.html"), name='password_reset_confirm'),
    path('reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name ="users\password_reset_complete.html"), name='password_reset_complete'),
    path('faq/', faq, name = 'faq' ),
    path('contact/', contactPage, name = 'contact' ),
    path('home', Home, name='home'),
    path('privacy/', views.privacy, name='privacy'),


    path('search/', SearchResultView.as_view(), name= 'search'),
    path('profilecard/', profilecard, name = 'profilecard'),
    path('<str:category>/<str:brand>/', ProductListView.as_view(), name= 'product-list'),
    path('<slug>/', PriceCompareView.as_view(), name='compare'),
    


    





]  

priceCompare/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Haggle.urls', namespace="Haggle")),
    #AUTHENTICATION
    path('accounts/', include('allauth.urls')),
]

Haggle/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify

# Create your models here.
class productDetails(models.Model):
    name = models.CharField(max_length= 5000  , null= False)
    imageLink = models.CharField(max_length= 5000 , null= False)
    ratings = models.CharField(max_length= 50 , null= True, blank=True)
    price = models.IntegerField(null= False)
    merchantName = models.CharField(max_length=40 , null= False)
    brand = models.CharField(max_length=40 , null= False )
    category = models.CharField(max_length= 50 , null= False)
    productLink = models.CharField(max_length= 5000, null=True)
    merchantLogo = models.CharField(max_length= 100, null=True)
    slug = models.SlugField(max_length=500,  null=True, unique=True, editable=False)


    def save(self, *args, **kwargs):
        konga_logo='https://www.konga.com/_next/static/images/62f8a0d88e07573b4d46735aa24f3f04.png'
        jumia_logo='https://1000logos.net/wp-content/uploads/2022/02/Jumia-Logo-768x432.png'
        slot_logo='https://slot.ng/media/wysiwyg/logo-icon-3_1_1_.png'
        self.slug = slugify(self.name+' '+str(self.id))
        if self.merchantName=='Konga':
            self.merchantLogo=konga_logo
        elif self.merchantName=='Jumia':
            self.merchantLogo=jumia_logo
        else:
            self.merchantLogo=slot_logo
        super().save(*args, **kwargs)
        pass 
    
    def get_absolute_url(self):
        return reverse("Haggle:compare", kwargs={"slug": self.slug})


class ProductComment(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey('productDetails', on_delete=models.CASCADE)

    def __str__(self):
        return 'Comment {} by {} '.format(self.body, self.author)

Haggle/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import  ProductComment


class CreateUserForm(UserCreationForm):
     def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({
            'name':'username',
            'id':'username',
            'class':'form-input',
        })

        self.fields["email"].widget.attrs.update({
            'name':'usernmae',
            'id':'username',
            'class':'form-input',
        })
        self.fields["password1"].widget.attrs.update({
            'name':'usernmae',
            'id':'username',
            'class':'form-input',
        })
        self.fields["password2"].widget.attrs.update({
            'name':'usernmae',
            'id':'username',
            'class':'form-input',
        })

        


     class Meta:
        model = User
        fields = [ 'username','first_name', 'last_name', 'email', 'password1', 'password2']




class CommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('author', 'body')

Haggle/views.py
from itertools import product
import queue
from unicodedata import category, name
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin

from django.db.models import Q
from django.core.paginator import Paginator




from multiprocessing import context
from webbrowser import get
from django.forms import Form
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import productDetails, ProductComment
from .forms import CommentForm
from django.urls import reverse
from django.views.generic import ListView
import random

# Create your views here.

#AUTHENTICATION
# def landing(request):
#     if request.user.is_authenticated:
#         return redirect('home')
#     else:
#         return render(request, 'users/landing.html')
def landing_page(request):
    return render(request,'index.html' )

@login_required(login_url='login')
def home(request):
    return render(request,'users/home.html' )

def signup(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' +  user)
                return redirect('login')
        context = {'form':form}
        return render(request, 'users/signup.html', context)


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:    
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username or Password is incorrect')
            
        context = {}
        return render(request, 'users/login.html', context)


def logoutuser(request):
    logout(request)


    return redirect('login')


def faq(request):
    return render(request, 'faq.html')

def profilecard(request):
    return render(request, 'profilecard.html')

def contactPage(request):
    return render(request, 'contact.html')
def Home(request):
    product = productDetails.objects.all()
    return render(request, 'index.html', {'product':product} )

def privacy(request):
    return render(request, 'privacy.html')


class SearchResultView(ListView):
    model = productDetails
    template_name = 'search.html'

    def get_queryset(self,mode='default'):
        search_value = self.request.GET.get('q')
        search_value = search_value.strip()
        if mode == 'default':
            results = list(productDetails.objects.filter(name__icontains=search_value))
            random.Random(4).shuffle(results)
        elif mode == 'low_to_high':
            results = productDetails.objects.filter(name__icontains=search_value)
        elif mode == 'high_to_low':
            results = productDetails.objects.filter(name__icontains=search_value)
        return results
    
    def get_context_data(self, **kwargs):
        product_list = self.get_queryset()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(product_list, 26)
        try:
            product = paginator.page(page)
        except PageNotAnInteger:
            product = paginator.page(1)
        except EmptyPage:
            product = paginator.page(paginator.num_pages)

        context=super().get_context_data(**kwargs)
        context['products']=product
        return context


    


class PriceCompareView(FormMixin, DetailView):
    model = productDetails
    template_name = 'comparison.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('Haggle:compare', kwargs={'slug': self.object.slug})

    def get_product(self, *args, **kwargs):
        return get_object_or_404(productDetails,slug=self.kwargs['slug'])
    
    def product_comparison_fetch(self):
        import re
        product=self.get_product()
        brand= product.brand
        merchant=product.merchantName
        name=product.name
        reduced_name=re.search(f'{brand.lower()}(.+)',name.lower()).group()
        brands_list=list(productDetails.objects.values_list('brand',flat=True).distinct())

        def get_valid_query(merchant):

            case_1=' '.join(reduced_name.split()[0:4])
            case_2=' '.join(reduced_name.split()[0:3])
            case_3=' '.join(reduced_name.split()[0:2])
            case_4= brand + ' ' + reduced_name.split()[2]

            if productDetails.objects.filter(Q(merchantName=merchant) & Q(name__icontains=case_1)).exists():
                query_value=case_1
            elif productDetails.objects.filter(Q(merchantName=merchant) & Q(name__icontains=case_2)).exists():
                query_value=case_2
            elif productDetails.objects.filter(Q(merchantName=merchant) & Q (name__icontains=case_3)).exists() and (case_3.split()[0]!='apple'):
                query_value=case_3
            elif productDetails.objects.filter(Q(merchantName=merchant) & Q(name__icontains=case_4)).exists():
                query_value= case_4
            else:
                query_value=brand
            
            return query_value

        slot_query_value=get_valid_query('Slot')
        jumia_query_value=get_valid_query('Jumia')
        konga_query_value=get_valid_query('Konga')
        Slot,Jumia,Konga=1,2,3
        query_map={Slot:[slot_query_value,'Slot'],Jumia:[jumia_query_value, 'Jumia'],Konga:[konga_query_value,'Konga']}
        

        
        for i in list(query_map):
            product_merchant_name=query_map[i][1]
            query_value=query_map[i][0].split()
            if query_map[i][0] in brands_list:
                i_new=productDetails.objects.filter(Q(merchantName=product_merchant_name) & Q(name__icontains=query_map[i][0]) & Q(price__lte=product.price) & Q(category=product.category)).order_by('-price')
                query_map[i_new]=query_map.pop(i)
            else:
                i_new=productDetails.objects.filter(Q(merchantName=product_merchant_name) & Q (name__icontains=query_map[i][0])).order_by('price')
                query_map[i_new]=query_map.pop(i)

        return_list=[]
        for i in query_map:
            if i.exists() and i[0].merchantName!=merchant:
                return_list.append(i[0])
        return return_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product=self.get_product()
        context['product'] = product
        context['comparisons'] = self.product_comparison_fetch()
        context['comments'] = ProductComment.objects.filter(product=product.id).order_by('created_on')
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save(commit=False)
        return super().form_valid(form)


class ProductListView(ListView):
    model = productDetails
    template_name = 'productlist.html'

    def get_queryset(self):
        results = list(productDetails.objects.filter(Q(category=self.kwargs.get('category')) & Q(brand__icontains=self.kwargs.get('brand')))) 
        random.Random(4).shuffle(results)
        return results

    
    
    def get_context_data(self, **kwargs):
        product_list = self.get_queryset()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(product_list, 26)
        try:
            product = paginator.page(page)
        except PageNotAnInteger:
            product = paginator.page(1)
        except EmptyPage:
            product = paginator.page(paginator.num_pages)

        context=super().get_context_data(**kwargs)
        context['products']=product
        return context

Haggle/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %}  {% endblock title %}</title>

        <script src="https://kit.fontawesome.com/773c20f948.js" crossorigin="anonymous"></script>
        <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
        <script src="https://code.iconify.design/iconify-icon/1.0.0-beta.2/iconify-icon.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&family=Open+Sans:wght@400;700&family=Poppins:wght@600&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://i.postimg.cc/kM10QcSD/hagglefavicon.png" type="">

      
        {% load static %}
        {% block stylesheeet %}
        
        {% endblock stylesheeet %}
        

        {% comment %} js and css scripts for the header {% endcomment %}
        <link rel="stylesheet" href= "{% static 'header-footer.css' %}">
        <script defer src= "{% static 'header-footer.js' %}"></script>

        {% comment %} for profilecard pages 
        
    
        {% comment %} for contact page 
        

        {% comment %} for product/search page 
        

        {% comment %} for privacy policy page 
        {% endcomment %}

        
    </head>


    <body>
      <header>
        <!-- FIRST NAVIGATION BAR -->
        <nav class="nav1">
            <div class="nav1-logo">
                <img src="https://i.postimg.cc/MZ7cXnfs/footer-logo.png" alt="">
            </div>
            
            <div class="nav1-1">
                <div class="nav1-icon">
                    <span class="iconify iconify3" data-icon="fa-regular:user"></span>
                </div>
                <a href="{% url 'Haggle:login' %}" class="create-account">Sign In</a>
                <a href="{% url 'Haggle:signup' %}" class="create-account">Register</a>
            </div>
   
            <span class="iconify menu-open" data-icon="bx:menu"></span>
            <span class="iconify menu-closed" data-icon="uim:multiply"></span>
            
        </nav>
        <!-- SECOND NAVIGATION BAR -->
        <nav class="nav2">
            <a href="{% url 'Haggle:landing' %}">Home</a>
            <select name="links" id="" size="1" onchange="window.location.href=this.value;">
                <option value="">All Categories</option>
                <optgroup label="Phones">
                    <option value="/phone/tecno">Tecno</option>
                    <option value="/phone/samsung">Samsung</option>
                    <option value="/phone/lenovo">Lenovo</option>
                    <option value="/phone/nokia">Nokia</option>
                    <option value="/phone/xiaomi">Xiaomi</option>
                    <option value="/phone/infinix">Infinix</option>
                    <option value="/phone/oppo">Oppo</option>
                    <option value="/phone/apple">Apple</option>
                </optgroup>
                <optgroup label="Laptops">
                    <option value="/laptop/asus">Asus</option>
                    <option value="/laptop/lenovo">Lenovo</option>
                    <option value="/laptop/hp">Hp</option>
                    <option value="/laptop/dell">Dell</option>
                    <option value="/laptop/apple">Apple</option>
                </optgroup>
                <optgroup label="Electronics"></optgroup>
            </select>
            <a href="aboutPage.html">About us</a>
            <a href="{% url 'Haggle:contact' %}">Contact</a>
            <a href="{% url 'Haggle:profilecard' %}" class="create-account2">User Profile</a>
            <a href="signin.html" class="create-account2">Sign in/Register</a>
            
           
           
        </nav>
        <!-- END OF HEADER -->
      </header>



      <main>
        {% block content %}
        
        {% endblock content %}

      </main>



        <!-- FOOTER -->
      <footer>
             <!-- FIRST FOOTER STARTS -->
                        <div class="news-letter">
                            <!-- NEWS LETTER SECTION -->
                            <div class="news-letter-details">
                                <h5>Newsletter</h5>
                                <small>To know more about new innovations at Haggle </small>
                            </div>
                            <div class="news-letter-email">
                                <div class="email-holder">
                                    <span class=" iconify iconify1 " data-icon="fa-regular:envelope"></span>
                                    <input type="email" name="" id="" placeholder="Enter your email " class="email-input">
                                </div>
                                
                                <button id="subscribe">Subscribe</button>
                            </div>
                        </div>
                        <!-- BLUE FOOTER DETAILS -->
                        <div class="first-footer-details">
                            <ul class="footer-ul">
                                <li class="title">About</li>
                                <li class="footer-tagline">Leading the innovation in <br> online customer shopping experience <br> in Nigeria</li>
                                
                            </ul>
                            <ul class="footer-ul">
                                <li class="title">Quick Links</li>
                                <li> <a href="{% url 'Haggle:faq' %}">FAQ</a></li>
                                <li> <a href="{% url 'Haggle:privacy' %}">Privacy policy</a></li>
                                <li> <a href="team.html">Meet Our Team</a></li>
                                <li> <a href="documentation.html">Documentation</a></li>
                            </ul>
                            <div class="socials">
                                <ul class="footer-ul">
                                    <li class="title">Support</li>
                                    <li > <a href="#"><span class=" iconify iconify2" data-icon="fa-regular:envelope"></span> info@haggle.com.ng</a></li>
                                    <li > <a href="#"><span class="iconify iconify2" data-icon="carbon:phone"></span>080-Haggle</a></li>
                                    <div>
        
                                </ul>
                                <div class="socials-icon">
                                    <div class="icon"><span class="iconify" data-icon="la:facebook-square" style="font-size:28px"></span></div>
                                    <div class="icon"><span class="iconify" data-icon="line-md:twitter" style="font-size:28px"></span></div>
                                    <div class="icon"><span class="iconify" data-icon="la:instagram" style="font-size:28px"></span></div>
                                    
                                </div>
                            </div> 
                        </div>
            <!-- SECOND FOOTER STARTS -->
            <div class="second-footer">
                <img src="https://i.postimg.cc/MZ7cXnfs/footer-logo.png" alt="" class="footer-logo">
                <p>&copy; 2022 Team 29 Nigeria. All rights reserved powered by Zuri-intership.com</p>
            </div>
        </footer>
        
    </body>
    </html>

Haggle/templates/comparison.html
{% extends 'base.html' %}
{% block title %} Comparison {% endblock title %}


{% block stylesheeet %}
    {% load static %}
    <link rel="stylesheet" href= "{% static 'comparison.css' %}">
    <link rel="stylesheet" href= "{% static 'accordion.css' %}">
    <script defer src= "{% static 'comparison.js' %}"></script>

{% endblock stylesheeet %}

{% block content %}
  
{%load humanize %}

<main class = "comparePage">  
    <section id="comparePageView">
        
        <a href="{{product.productLink}}"><img class = 'comparisonImage' src="{{ product.imageLink }}" alt=""></a> 
        <aside>
               
            <div class="share-icon"> 
                <span class="iconify" data-icon="cil:share-alt" id="first-icon"></span>
                <span class="iconify" data-icon="fluent:comment-add-48-regular"></span>
            </div><br>

            <h1>{{product.name}}</h1><br>
            <span class = 'comparisonCard'>
                <p> &#8358;{{product.price|intcomma}}</p>
                <img src = '{{product.merchantLogo}}'/>
            </span>
            

            {% for products in comparisons %}
            <a href="{{products.productLink}}" class = 'comparisonCard'>   
                <p> &#8358;{{products.price|intcomma}}</p> 
                <img src = '{{products.merchantLogo}}'/>

                 

            </a>
            
            {% endfor %}
        </aside>

    </section>
    
    
</main>    
{% endblock %}

Haggle/templates/contact.html
{% extends 'base.html' %}
  
{% block title %} Contact {% endblock title %}


{% block stylesheeet %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'contact.css' %}">
{% endblock stylesheeet %}

{% block content %}
<div class="main">
    <div class="main-img">
        <img src="https://i.postimg.cc/3xjYSVKK/IMAGE.png" alt="" class="contact-img">
    </div>
    <div class="contact-box">
        <h2>CONTACT US</h2>
        <form action="">
            <div class="name">
                <div class="name-hold">
                    <label for="firstname">First name</label>
                    <input type="text" name="" placeholder="John"id="" minlength="3" required>
                </div>
                <div class="name-hold">
                    <label for="lastname">Last name</label>
                    <input type="text" name="" placeholder="Doe"id="" minlength="3" required>
                </div>
            </div>
            
            <label for="email">Email</label>
            <input type="email" name="" id="" placeholder="johndoe@doe.com" required>
            <label for="subect">Subject</label>
            <input type="text" name="" id="" minlength="3" required>
            <label for="message">Message/Enquiry</label>
            <textarea name="message" id="" class="msg-box"></textarea>
            <div class="btn-hold">
                <button  value="submit" class="btn-submit" required>Submit</button>
            </div>
            
        </form>
    </div>
    
</div>
{% endblock content %}

Haggle/templates/faq.html
{% extends 'base.html' %}
  
{% block title %} FAQ {% endblock title %}


{% block stylesheeet %}
  {% load static %}
  {% comment %} for faq pages {% endcomment %}
  <link rel="stylesheet" href= "{% static 'faq.css' %}" >
  <script defer src= "{% static 'faq.js' %}" ></script>
{% endblock stylesheeet %}


  


{% block content %}
<div class="faqContainer"> 
  <h1>Frequently Asked Questions</h1>
  <div class="faqContent"> 
    <div class="faqQuestion"><h3>How can I use Haggle ?</h3></div>
    <div class="faqAnswer">
      <p>
        Haggle is tour one stop place to get updated 
        on your favourite product current rates across various platforms. We 
        give you upsated market prices and choice to make well informed decisions before 
        purchase. <br> Watch this tutorial on how to make best out of this platform here.
      </p>
    </div>
  </div>
  <div class="faqContent">
    <div class="faqQuestion"><h3>How can I create an account on Haggle ?</h3></div>
    <div class="faqAnswer">
      <p>
        To create an account, kindly click on the create an account text on the 
        screen, insert your mail address, password and sign in.<br>If you are having issues 
        creating an account, kindly contact us here.
      </p>
    </div>
  </div>

  <div class="faqContent">
    <div class="faqQuestion"><h3>How can i create an account on Haggle ? </h3></div>
    <div class="faqAnswer">
      <p>
        To create an account, kindly click on the create an account text on the 
        screen, insert your mail address, password and sign in.<br>If you are having issues 
        creating an account, kindly contact us here.
      </p>
    </div>
  </div>
</div> 
{% endblock %} 

Haggle/templates/productlist.html
{% extends 'base.html' %}


{% block stylesheeet %}
  {% load static %}
  <link rel="stylesheet" href= "{% static 'product.css' %}">
{% endblock stylesheeet %}

  {% block content %}
    {%load humanize %}

    <div class="productCardContainer">
      {% for product in products %}
       <a href="{{product.get_absolute_url}}">
          <h1>{{ product.name }}</h1>
          <figure>
            <img src="{{ product.imageLink }}" alt="product image">
          </figure>

          <h3> &#8358;{{ product.price|intcomma }}</h3>
          <img src = '{{product.merchantLogo}}'/>
          
        </a>
      {% endfor %}
      </div>
      


    {% comment %} whoever  structured this page needs to work on writing clearner codes. {% endcomment %}
    {% if products.has_other_pages %}
        <div class="pagination">
          {% if products.has_previous %}
            <a href="?page={{ products.previous_page_number }}" class="previous-and-next-page-button">
                              <span class="iconify" data-icon="wi:direction-left"></span>
                              <p>Previous</p>
          {% else %}
            <div class="page-item disabled"><span>&laquo;</span></div>
          {% endif %}
          {% for i in products.paginator.page_range %}
            {% if products.number == i %}
              <p class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></p>
            {% else %}
              <a href="?page={{ i }}" class="active">{{ i }}</a>
            {% endif %}
          {% endfor %}
          {% if products.has_next %}
            
            <a href="?page={{ products.next_page_number }}" class="previous-and-next-page-button">
                              <p>Next</p> <span class="iconify" data-icon="wi:direction-left" data-rotate="180deg"></span>
                          </a>
          {% else %}
            <p class="page-item disabled"><span>&raquo;</span></p>
          {% endif %}
        </div>
        {% endif %}

  {% endblock %}

Haggle/templates/profilecard.html
{% extends 'base.html' %}
  
{% block title %} PROFILE CARD {% endblock title %}

{% block stylesheeet %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'profilecard.css' %}" >
{% endblock stylesheeet %}




{% block content %}
    <!-- MAIN FOR PROFILE CARD -->
    <main>
      <!-- FIRST ITEM ON THE PAGE -->
      <div class="profile">
        <div class="profile-pic">
          <span class="iconify" data-icon="fa-regular:user"></span>
        </div>
        <p class="join">Joined 2020-07-30</p>
      </div>
      <!-- BORDER LINE -->
      <hr />

      <!-- FORM FIELDS -->
      <form action="">
        <div class="form-fields">
          <div class="details-name">
            <div class="f-name">
              <label for="fname">First Name</label>
              <input
                type="text"
                name="fname"
                placeholder="John"
                class="field"
                required
              />
            </div>
            <div class="l-name">
              <label for="lname"> Last Name</label>
              <input
                type="text"
                name="lname"
                placeholder="Doe"
                class="field"
                required
              />
            </div>
          </div>
          <div class="details-contact">
            <div class="email-add">
              <label for="email">Email Address</label>
              <input
                type="email"
                name="email"
                placeholder="Johndoe@mail.com"
                class="field"
                required
              />
            </div>
            <div class="phone-no">
              <label for="usernamee"> Username </label>
              <input
                type="text"
                name="usernamee"
                placeholder="joh"
                class="field"
                required
              />
            </div>
          </div>
          <div class="details-verify">
            <div class="pass-wd">
              <label for="passwd">Password</label>
              <input
                type="password"
                name="passwd"
                placeholder="John123!"
                class="field"
                required
              />
              <span
                class="iconify"
                data-icon="clarity:eye-show-line"
                id="icon1"
              ></span>
            </div>
            <div class="gender">
              <label for="gender">Gender</label>
              <input
                type="text"
                name="gender"
                placeholder="female"
                class="field"
                required
              />
            </div>
          </div>
        </div>
      </form>
    </main>
 {% endblock %} 